export default [
    {
        selector: 'title',
        type: 'text',
        label: 'نام',
        col: 4,
        isRequired: true,
        editable: true,
    },
    {
        selector: 'bank_id',
        type: 'select',
        label: 'بانک متصل کننده',
        col: 4,
        options: `/api/v4/banks?page_size=9999`,
        optionLabelSelector: 'name',
        isRequired: true,
        editable: true,
    },
    {
        selector: 'brand',
        type: 'text',
        label: 'برند',
        col: 4,
        isRequired: true,
        editable: true,
    },
    {
        selector: 'model',
        type: 'text',
        label: 'مدل',
        col: 4,
        isRequired: true,
        editable: true,
    },
    {
        selector: 'serial',
        type: 'text',
        label: 'سریال',
        col: 4,
        isRequired: true,
        editable: true,
    },
    {
        selector: 'terminal_id',
        type: 'text',
        label: 'ترمینال',
        col: 4,
        isRequired: true,
        editable: true,
    },
    {
        selector: 'imei',
        type: 'text',
        label: 'IME',
        col: 4,
        isRequired: true,
        editable: true,
    },
]
