export const GET_DATA_STARTED = "@/SMARTCRUD/DATATABLE/GET/STARTED";
export const GET_DATA_SUCCESS = "@/SMARTCRUD/DATATABLE/GET/SUCCESS";
export const GET_DATA_FAILED = "@/SMARTCRUD/DATATABLE/GET/FAILED";

export const GET_SMART_CRUD_DATA_STARTED = "@/SMARTCRUD/DATATABLE/SMART/CRUD/GET/STARTED";
export const GET_SMART_CRUD_DATA_SUCCESS = "@/SMARTCRUD/DATATABLE/SMART/CRUD/GET/SUCCESS";
export const GET_SMART_CRUD_DATA_FAILED = "@/SMARTCRUD/DATATABLE/SMART/CRUD/GET/FAILED";

export const GET_MERCHANTS_STARTED = "@/SMARTCRUD/DATATABLE/GET/MERCHANTS/STARTED";
export const GET_MERCHANTS_SUCCESS = "@/SMARTCRUD/DATATABLE/GET/MERCHANTS/SUCCESS";
export const GET_MERCHANTS_FAILED = "@/SMARTCRUD/DATATABLE/GET/MERCHANTS/FAILED";

export const SET_PAGINATION_TO = "@/SMARTCRUD/PAGINATION/SET"
export const UPDATE_A_ROW_STATE = "@/SMARTCRUD/DATATABLE/UPDATE/ROW/STATE"
export const RELOAD_DATATABLE = "@/SMARTCRUD/DATATABLE/RELOAD/DATA";

export const CREATE_STARTED = "@/SMARTCRUD/CREATE/STARTED";
export const CREATE_SUCCESS = "@/SMARTCRUD/CREATE/SUCCESS";
export const CREATE_FAILED = "@/SMARTCRUD/CREATE/FAILED";

export const EDIT_STARTED = "@/SMARTCRUD/EDIT/STARTED";
export const EDIT_SUCCESS = "@/SMARTCRUD/EDIT/SUCCESS";
export const EDIT_FAILED = "@/SMARTCRUD/EDIT/FAILED";

export const DELETE_STARTED = "@/SMARTCRUD/DELETE/STARTED";
export const DELETE_SUCCESS = "@/SMARTCRUD/DELETE/SUCCESS";
export const DELETE_FAILED = "@/SMARTCRUD/DELETE/FAILED";


export const GET_MORPH_STARTED = "@/SMARTCRUD/MORPH/GET/STARTED";
export const GET_MORPH_SUCCESS = "@/SMARTCRUD/MORPH/GET/SUCCESS";
export const GET_MORPH_FAILED = "@/SMARTCRUD/MORPH/GET/FAILED";

export const POST_MORPH_STARTED = "@/SMARTCRUD/MORPH/POST/STARTED";
export const POST_MORPH_SUCCESS = "@/SMARTCRUD/MORPH/POST/SUCCESS";
export const POST_MORPH_FAILED = "@/SMARTCRUD/MORPH/POST/FAILED";

export const EDIT_MORPH_STARTED = "@/SMARTCRUD/MORPH/EDIT/STARTED";
export const EDIT_MORPH_SUCCESS = "@/SMARTCRUD/MORPH/EDIT/SUCCESS";
export const EDIT_MORPH_FAILED = "@/SMARTCRUD/MORPH/EDIT/FAILED";

export const DELETE_MORPH_STARTED = "@/SMARTCRUD/MORPH/DELETE/STARTED";
export const DELETE_MORPH_SUCCESS = "@/SMARTCRUD/MORPH/DELETE/SUCCESS";
export const DELETE_MORPH_FAILED = "@/SMARTCRUD/MORPH/DELETE/FAILED";


export const DELETE_HAS_MANY_RELATION_ITEM_STARTED = "@/SMARTCRUD/DELETE/HASMANY/RELATION/ITEM/STARTED";
export const DELETE_HAS_MANY_RELATION_ITEM_SUCCESS = "@/SMARTCRUD/DELETE/HASMANY/RELATION/ITEM/SUCCESS";
export const DELETE_HAS_MANY_RELATION_ITEM_FAILED = "@/SMARTCRUD/DELETE/HASMANY/RELATION/ITEM/FAILED";

export const SET_MEDIA_MODAL_SHOW_TO = "@/SMARTCRUD/SET/MEDIA/MODAL/TO";

export const MEDIA_GET_LIST_STARTED = "@/SMARTCRUD/MEDIA/GET/LIST/STARTED";
export const MEDIA_GET_LIST_SUCCESS = "@/SMARTCRUD/MEDIA/GET/LIST/SUCCESS";
export const MEDIA_GET_LIST_FAILED = "@/SMARTCRUD/MEDIA/GET/LIST/FAILED";

export const MEDIA_UPLOAD_STARTED = "@/SMARTCRUD/MEDIA/UPLOAD/STARTED";
export const MEDIA_UPLOAD_SUCCESS = "@/SMARTCRUD/MEDIA/UPLOAD/SUCCESS";
export const MEDIA_UPLOAD_FAILED = "@/SMARTCRUD/MEDIA/UPLOAD/FAILED";

export const MEDIA_DELETE_STARTED = "@/SMARTCRUD/MEDIA/DETACH/STARTED";
export const MEDIA_DELETE_SUCCESS = "@/SMARTCRUD/MEDIA/DETACH/SUCCESS";
export const MEDIA_DELETE_FAILED = "@/SMARTCRUD/MEDIA/DETACH/FAILED";

export const MEDIA_UPDATE_INFORMATION_STARTED = "@/SMARTCRUD/MEDIA/UPDATE/INFORMATION/STARTED";
export const MEDIA_UPDATE_INFORMATION_SUCCESS = "@/SMARTCRUD/MEDIA/UPDATE/INFORMATION/SUCCESS";
export const MEDIA_UPDATE_INFORMATION_FAILED = "@/SMARTCRUD/MEDIA/UPDATE/INFORMATION/FAILED";

export const MEDIA_UPDATE_SHEAR_WITH_STARTED = "@/SMARTCRUD/MEDIA/SHEAR/WITH/STARTED";
export const MEDIA_UPDATE_SHEAR_WITH_SUCCESS = "@/SMARTCRUD/MEDIA/SHEAR/WITH/SUCCESS";
export const MEDIA_UPDATE_SHEAR_WITH_FAILED = "@/SMARTCRUD/MEDIA/SHEAR/WITH/FAILED";

export const MEDIA_SAVE_TO_GALLERY_STARTED = "@/SMARTCRUD/MEDIA/SAVE/TO/GALLERY/STARTED";
export const MEDIA_SAVE_TO_GALLERY_SUCCESS = "@/SMARTCRUD/MEDIA/SAVE/TO/GALLERY/SUCCESS";
export const MEDIA_SAVE_TO_GALELRY_FAILED = "@/SMARTCRUD/MEDIA/SAVE/TO/GALLERY/FAILED";